sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=dmonteiropaddle/test-project-shippable
    - REGISTRY_USER=dmonteiropaddle
    - REGISTRY_PASS=$DOCKERPASS
    - secret: "<something long>"

before_install:
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64.zip
  - mv terraform terraform-ecs-cluster/
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

script:
  - docker build --pull --tag "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker push "${IMAGE_NAME}:latest"
  - chmod u+x terraform-ecs-cluster/build.sh
  - ./terraform-ecs-cluster/build.sh

after_script:
  - ./terraform-ecs-cluster/destroy.sh